name: "Vprofile IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - "terraform/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: $${{ secrets.BUCKET_TF_STATE }}}
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: "vprofileldn-eks"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2

      - name: "Terraform Init"
        id: init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}" #-backend-config="key=terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

      - name: "Terraform format"
        id: format
        run: terraform format -check

      - name: "Terraform Validate"
        id: validate
        run: terraform validate

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -no-color -input=false -out="terraform.tfplan"
        continue-on-error: true

      - name: "Terraform Plan status"
        if: steps.plan.outcome == 'failure'
        run: exit 1

      #- name: "Terraform Apply"
      #  id: apply
      #  run: terraform apply -auto-approve "terraform.tfplan"
  